#[derive(Debug, Clone, PartialEq, Default)]
pub struct ModelInput {
    pub key: Option<String>,
    pub arr_name: Option<String>,
    pub path: f32,
    pub phrase: Option<String>,
    pub levels: f32,
    pub unique_levels: f32,
    pub length_ms: f32,
    pub length_beats: f32,
    pub tempo: f32,
    pub notes: f32,
    pub repeated_notes: f32,
    pub chords: f32,
    pub repeated_chords: f32,
    pub tech_count: f32,
    pub palm_mutes: f32,
    pub bends: f32,
    pub harmonics: f32,
    pub pharmonics: f32,
    pub taps: f32,
    pub tremolos: f32,
    pub vibratos: f32,
    pub slides: f32,
    pub unp_slides: f32,
    pub ignored: f32,
    pub anchors: f32,
    pub max_chord_strings: f32,
    pub solo: Option<String>,
}
